# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Cheolhong Min (민철홍)
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website.
baseurl: "" # the subpath of the site
url: "https://cheolhong0916.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: CV
      slug: /assets/cv_240819.pdf
    - name: Publications
      slug: /publications


footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: cheolhong0916@gmail.com
  follow:
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername
    - type: github
      name: GitHub
      link: http://github.com/cheolhong0916

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
